name: flutter_widget
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  json_annotation: ^0.2.2

dev_dependencies:

  build_runner: ^0.7.6
  json_serializable: ^0.3.2

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/Basics.json
    - assets/materialDesign.json
    - assets/Texts.json
    - assets/Scrollings.json

    - assets/Layout.json
    - images/image1.jpg



